### PR TITLE
Add beverages

### PR DESCRIPTION
**Pull request by kidstylex**
Add some beverages

### CODE REVIEW

**Comment by KOngTNP** [comment]
it ok.

**Comment by theethaj** [comment]
Please add your hyperlink to README.md

**Comment by theethaj** [comment]
Please fill your name, role and Github ID to README.md

**Comment by theethaj** [comment]
Please add your link to your Github profile.

**Comment by kidstylex** [comment]
> Please add your hyperlink to README.md
> Please fill your name, role and Github ID to README.md
> Please add your link to your Github profile.

done.

**Comment by theethaj** [comment]
GREAT!

**Pull request merged**
